In [9]:
#pandas:library di python

In [23]:
import pandas as pd

#Soal 1: buatlah Objek DataFrames</h2>

In [24]:
# Contoh Membuat dataframes dari dictionary
df = pd.DataFrame({'NAMA':['adi','budi','cici'], 'Nilai':[80,90,100]})
display(df)

   NAMA  Nilai
0   adi     80
1  budi     90
2  cici    100

In [26]:
df_delvin = pd.DataFrame({'First Name':['Mochammad Delvin'], 'Last Name':['Farhan Akbar']})
display(df_delvin)

         First Name     Last Name
0  Mochammad Delvin  Farhan Akbar

<h2>Soal 2:Bacalah data dari file</h2>

Download file bernama [diamonds.csv](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd)

In [25]:
url = 'https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd'
variabel = pd.read_csv(url)
display(variabel.head())

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

# Soal 3:DataFrame vs Series</h2>



1.   Perbedaan DataFrame dan series
2.   Buatlah series

jawab:

In [14]:
#contoh series
ini_series = pd.Series([1,2,3,4],index=['a','b','c','d'])
ini_series

a    1
b    2
c    3
d    4
dtype: int64

In [27]:
my_series = pd.Series([10, 20, 30, 40], index=['w', 'x', 'y', 'z'])
display(my_series)

w    10
x    20
y    30
z    40
dtype: int64

# Soal 4:Pemeriksaan Data Sederhana</h2>

a)ambilah 5 baris pertama data diamonds.csv yang tadi anda baca dengan .head

In [28]:
display(variabel.head(5))

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

b)ambilah 5 baris terakhir data diamonds.csv yang tadi anda baca dengan .tail

In [29]:
display(variabel.tail(5))

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

c)ambillah baris pertama kolom carat

In [18]:
#contoh ambil data baris pertama
display(variabel[['price']].head(1))

   price
0    326

In [30]:
display(variabel[['carat']].head(1))

   carat
0   0.23

d)ambillah baris terakhir dari kolom carat

In [20]:
#contoh ambil data baris terakhir dari kolom color
display(variabel[['color']].tail(1))

      color
53939     D

In [31]:
display(variabel[['carat']].tail(1))

       carat
53939   0.75

<h2>Soal 5:Apa itu Deskriptif Statistik?</h2>

jawab:  
Statistika Deskriptif adalah metode yang digunakan untuk merangkum, mengatur, dan mendeskripsikan fitur utama dari kumpulan data melalui angka ringkasan (seperti mean, median, modus) dan visualisasi (seperti tabel atau grafik) agar informasi lebih mudah dipahami.

<h2>Soal 6 : Practice Deskriptif Statistik</h2>

1.   Praktikkanlah cara menampilkan deskriptif statistik di python dengan data csv yang sudah anda baca dengan .describe()

In [32]:
display(variabel.describe())

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000